In [11]:
import numpy as np
a=np.zeros(5)   #initializes the array with all values as zero.parameters=(kernel_size,dtype)
print(a)
b=np.ones((2,3))   #initializes the array with all values as ones.parameters=(kernel_size,dtype)
print(b)
c=np.full((3,3),9)  #initializes the array with all values as the specified constant.parameters=(kernel_size,constant value)
print(c)
f=np.full_like(b,3,dtype='uint8')
print(f)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[3 3 3]
 [3 3 3]]


In [13]:
#Random decimal integers
d=np.random.rand(3,3,3)   
print(d)
e=np.random.random_sample(c.shape)
print(e)

[[[0.66208068 0.5779438  0.72264282]
  [0.87253526 0.45235244 0.96903694]
  [0.0782451  0.01605002 0.3869798 ]]

 [[0.30134619 0.5855254  0.97865375]
  [0.16353191 0.08913825 0.19078973]
  [0.91451931 0.75412679 0.31374822]]

 [[0.16511928 0.24057168 0.29552273]
  [0.00799469 0.08194121 0.46593626]
  [0.30899348 0.21390221 0.54018888]]]
[[0.53874969 0.8081001  0.32199023]
 [0.1539699  0.51223655 0.34716672]
 [0.27629632 0.0653216  0.7174355 ]]


In [20]:
#Random integer numbers
i1=np.random.randint(9,size=(2,3))
print(i1)

[[3 5 1]
 [0 3 8]]


In [21]:
#identity matrix
id=np.identity(4)
print(id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
#repeat the array
l=np.array([[1,2,3,4]])
rp=np.repeat(l,3,axis=0)
print(rp)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [27]:
op=np.ones((5,5))
middle=np.zeros((3,3))
middle[1,1]=9
op[1:4,1:4]=middle
print(op)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Statistics

In [34]:
stat=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np.min(stat,axis=1)) 
print(np.max(stat,axis=0)) 
print(np.sum(stat,axis=1)) 

[1 7]
[ 7  8  9 10 11 12]
[21 57]


##### Reorganising Arrays

In [39]:
inp=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(inp)
out=inp.reshape(6,2)
print(out)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [44]:
n1=np.array([1,2,3,4,5,6])
n2=np.array([7,8,9,10,11,12])
np.hstack((n1,n2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

##### Input from text file

In [55]:
filetext=np.genfromtxt('text1.txt',delimiter=',')
print(filetext)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


##### Boolean Masking and Advanced indexing

In [56]:
print(filetext>5)
print(filetext[filetext>5])

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 6.  7.  8.  9. 10. 11. 12.]


In [69]:
#Indexing with a list
print(input[[2,2],[1,1]])

[10. 10.]
