In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b[0,:]) #prints a specific row
print(b[:,2]) #prints a specific column
print(b[1,:-1:2]) #startindex:endindex:step
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #3d array
print(c[:,1,:]) 
print(c[:,0,:])
print(c[0,1,:])

[1 2 3]
[1 2 3 4]
[3 7]
[5 7]
[[3 4]
 [7 8]]
[[1 2]
 [5 6]]
[3 4]
